services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: candidate_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: